.\" Process this file with
.\" groff -man -Tascii foo.1
.TH "Somax-nextitem" "1" "2007 Jan 28" "" "User Command"
.SH "NAME"
.LP 
Somax\-nextitem \- tool designed for making operations on next items played from Somad, in a graphical manner.
.SH "DESCRIPTION"
.LP 
Somax\-nextitem is a tool designed for making operations on the next items to plays from Somad, in a graphical manner. 

This software aims to be a minimal version of Somax, and works with the items (songs for example) which Somad will play later. You can make a kind of playlist with it.

It has be written in the GTK+ 2.x graphics libraries. and are projected to be easy and functional.

There is'nt any command\-line option for start Somax\-nextitem. Somax\-nextitem may be run too from the Somax main window.
.SH "OPTIONS"
.LP 
There is'nt comand\-line options for start Somax\-nextitem, but you need to specify some parameters for start it. At start time Somax\-nextitem present a nice graphic window, that is the same that Somax itself present. For know the parameters that you need to put in it, you can refer to the \fBSomax(1)\fR man page.
.P
After this parameter's window is acepted, a nice window appears, with all the options to fill a playlist for Somad.
.SH "FILES"
.LP 
.IP \fI~/.somax/\fP 
In the ~/.somax/ directory, all the Somax related applications stores its config files.
.SH "AUTHORS"
.LP 
.nf 
Somad written by Andrea Marchesini <bakunin@autistici.org>
Man page written by Martin Zelaia <martintxo@sindominio.net>
.SH "SEE ALSO"
.LP 
.BR somad (1),
.BR soma.cfg (5),
.BR palinsesto.cfg (5),
.BR spot.cfg (5),
.BR somaclient (1),
.BR somax (1)
.BR somax\-config (1)
.BR somax\-editor (1)

http://www.somasuite.org/
